# Generated by Django 5.0 on 2023-12-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='fuelNote',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='mevsim',
            field=models.CharField(default='mevsim', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='model_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='performance',
            field=models.CharField(default='Yüksek', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='tireSpecs',
            field=models.CharField(default='250 50 R15', max_length=10),
            preserve_default=False,
        ),
    ]
