# Generated by Django 5.0 on 2023-12-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tire_fuelnote_tire_mevsim_tire_model_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
