# Generated by Django 5.0 on 2023-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_tire_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=400)),
                ('fuelType', models.CharField(max_length=100)),
                ('tireSpecs', models.CharField(max_length=10)),
                ('tireWidth', models.IntegerField()),
                ('tireHeight', models.IntegerField()),
                ('rimSize', models.IntegerField()),
            ],
        ),
    ]
